### ISSUE TITLE
Possible mismatch between pycontrol and pyphotometry data

### ISSUE THREAD

**Issue by teristam** [juliencarponcy/trialexp#10]
### Description

Analysis in the test session-based folders failed because of mismatch between pycontrol and pyphotometry data.

Example:
`Julien\Data\head-fixed\_Other\test_folder\by_session_folder\JC317L-2022-12-11-212623`

pycontrol folder is from `212623`  but photometry data is from `202713`. Probably need to have more check (e.g. trying to create a Rsync object) than just relying on file timestamp?

**Comment by juliencarponcy** [comment]
I don't forget about this one, we will probably have to write test and adding the "same day" condition at the very least. I will possibly address after I'm back in France.
It wont affect results since rsync won't match anyway.
And yes, in the past pipelines I had before a sync_photometry functions which was first finding file then matching rsync. Then I just took out the generic find_matching_files out of it. 
Trying to align right after matching is indeed a good approach

**Comment by teristam** [comment]
Do you want me to help work on this? I think it is good if we can have some functional scripts to copy the pycontrol/pyphotometry data to a session based folder so that we can run the new pipeline on our on-going experiements
